### ISSUE TITLE
Fix Shell ReflectionMethod::__construct default null argument in hasMethod

### ISSUE THREAD

**Issue by josemv92** [kamilwylegala/cakephp2-php8#10]
On CakePHP's Shell commands, the default behavior is to run the `main`function when either a method is not provided when executed which is failing when running the code on PHP 8.1.

With PHP 8.1, the ReflectionMethod __construct expects the `$method` argument to be string when an object is passed as the first parameter.

The problem found in the CakePHP code is that when a Shell command is called without the method to execute, the method is sent as NULL, causing the following error:

```
# ./app/Console/cake Foo
Error: ReflectionMethod::__construct(): Argument #2 ($method) cannot be null when argument #1 ($objectOrMethod) is an object
#0 /var/www/html/lib/Cake/Console/Shell.php(358): ReflectionMethod->__construct(Object(FooShell), NULL)
#1 /var/www/html/lib/Cake/Console/Shell.php(423): Shell->hasMethod(NULL)
#2 /var/www/html/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand(NULL, Array)
#3 /var/www/html/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 /var/www/html/app/Console/cake.php(47): ShellDispatcher::run(Array)
#5 {main}
```

**Comment by josemv92** [comment]
Didn't see any information as how to send pull requests for this fork (if allowed) so I raised this issue for awareness.

**Comment by kamilwylegala** [comment]
Hey @josemv92 

Pull requests are welcome. If you already fixed it on your side please send pull request. Thanks in advance!

If not I could take a look on this issue in the evening (CET)

**Comment by josemv92** [comment]
Created PR #11 .

Let me know your thoughts and/or feel free to do modifications.

**Comment by kamilwylegala** [comment]
Merged. Closing. Thanks for your contribution.
