### ISSUE TITLE
Custom RouteClasses

### ISSUE THREAD

**Issue by kevin33028** [kamilwylegala/cakephp2-php8#15]
When using custom route classes and passing back a controller and action parameter to direct the page to the correct controller/action, it thinks the controller and action don't exist.

**Comment by kamilwylegala** [comment]
Could you share some code to reproduce it? Is it related to PHP8 upgrade?

**Comment by kevin33028** [comment]
Yes, it is related to PHP 8.1. The app folder is directly copied from a PHP 7.4 Server that is in production with no issues. 

in routes, we use a route class to determine the course of action, we don't actually use it for all of navigation, its just set this way for testing at the moment. 


**routes.php**
Router::connect('/*',   "NOTE... THERE SHOULD BE A STAR HERE AFTER THE / but it isn't showing."
array('controller' => 'business', 'action' => 'search'),
array('pass' => array('*'), 'routeClass' => 'BusinessRoute'));


**New File located under app/Lib/Route named BusinessRoute.php  (Condensed for testing purposes)**


App::uses('CakeRoute', 'Routing/Route');

class BusinessRoute extends CakeRoute 
{
  public function parse($url) 
  {
        $params = parent::parse($url);


	if( empty($params) ) 
            return false;
      $params['controller']='pages';
      $params['action']='home';
     return $params;
    }

}

**Comment by kamilwylegala** [comment]
OK so point of this custom route is to just redirect to different controller?

I.e. route is configured to match custom route class on `/business/search` but in route class you want to parse it and redirect to: `/home`. Right?

**Comment by kevin33028** [comment]
This is just the test case, but yes, that is the point of custom routes. 

Normally this route will just move around in the same controller. i.e something may not go to the search action, but go to our searchgeo action if the url has geo data in it.  

The BusinessRoute class checks various things, like DB, static variables, or session variables to determine if there is a deviance in the standard route.

**Comment by kamilwylegala** [comment]
OK, I understand. I wasn't familiar with this feature. Is there any errror/exception you get from framework?

**Comment by kevin33028** [comment]
Just the standard no method found message. Image attached. 

![Capture](https://user-images.githubusercontent.com/80540400/156779760-326ea041-c2b9-40a1-99a0-786cb54c71d0.JPG)

**Comment by kamilwylegala** [comment]
If think such error is expected. Routing to pages controller is configured differently. Cake reponse is correct - there is missing view `home`. If you want to configure redirect to pages controller following code is required:
```php
 $params = parent::parse($url);

$params["controller"] = "pages";
$params["action"] = "display";
$params["pass"] = ["home"];

return $params;
```

I configured similar example in my project:

Added custom route to `app/Routing/Route/TestCustomRoute.php`:
```php
<?php

App::uses('CakeRoute', 'Routing/Route');

class TestCustomRoute extends CakeRoute
{
    public function parse($url)
    {
        $params = parent::parse($url);

        $params["controller"] = "pages";
        $params["action"] = "display";
        $params["pass"] = ["termsAndConditions"];

        return $params;
    }
}
```

Then in `routes.php`:
```php
App::uses('TestCustomRoute', "Routing/Route");

Router::connect(
    '/test',
    ['controller' => 'pages', 'action' => 'display', "privacy"],
    ['routeClass' => 'TestCustomRoute']
);
```

When I enter in the browser `/test` it works as expected, initially I get request to render `privacy` page (in debug mode in custom route), then it gets rewritten to `termsAndCondition` and browser correctly shows the page.

**Comment by kevin33028** [comment]
This is not correct. I only changed this to Pages home as example and the function home does exist in my pages controller. You can use any controller/action and it will throw the same error. 

I will do a fresh install of cake and not use my existing application which uses this routing currently and see if there is some issues in translation.

**Comment by kamilwylegala** [comment]
But my example above works. I correctly get redirected to different action. 

Did you have a chance to debug this problem step by step with xdebug?

**Comment by kevin33028** [comment]
Try changing your action and not just the variable passed to it. You are asking for Controller: Pages and Action: Display in both your routes and in your custom route. 

Try changing your Action in the Custom Route.

**Comment by kevin33028** [comment]
It seems to be working in a new test environment for me, I will debug more on the existing code and report back.

**Comment by kevin33028** [comment]
I FOUND THE PROBLEM!!! YAY!!

When you change the array pass in $params to an associative array from a numeric array it causes this error to happen. So if I provide: 

**Works:**
$params['pass']=array(0=>'Orlando');  

**Does Not Work**
$params['pass']=array('city_name'=>'Orlando'); // This is what throws the error.


The Current site has it built this way as it was never an issue in PHP 5/7 and we pass quite a bit of variables back in the params array from the routing.

**Comment by kamilwylegala** [comment]
OK I suspect underneath there is `call_user_func_array`. Similar situation was here: https://github.com/kamilwylegala/cakephp2-php8/commit/d9247a0832070486cb15472a53507b83e0fb8179

In that case indeed this is issue related to PHP8. Did you find specific place where `array_values` should be applied?

**Comment by kevin33028** [comment]
I searched all the call_user_func_array in the lib folder and none of those seem to be affecting this code. I am still trying to trace it down to understand where in the chain of functions the error occurs. 

I found that the parseParams Function in \lib\Cake\RoutingDispatcher.php receives the associate array of params and nothing errors out here, but I am not sure what calls the parseParams function.

**Comment by kamilwylegala** [comment]
I debugged code a little bit and I think invalid code is in:
```
\Controller::invokeAction //line 489
```

Could you check if this helps in your project:
```php
return $method->invokeArgs($this, array_values($request->params['pass'])); //line 499
```

I think code before with assoc array was trying to run controller's action with named parameter (in your case `city_name`).

Exception makes things clear:
![image](https://user-images.githubusercontent.com/10462494/157121662-b7043baa-9b0a-4afb-befb-dc67f5a04379.png)

Please confirm if it works for you. Then I can push fix to master branch.

**Comment by kevin33028** [comment]
That was it!! You are the man!

**Comment by kevin33028** [comment]
We would like to send you something nice as a thank you for this repository and your help, please email me at kevin@chamberofcommerce.com

**Comment by kamilwylegala** [comment]
I just pushed fix to master. You can review the code here: https://github.com/kamilwylegala/cakephp2-php8/commit/a5a0ccd551728bdb5955ae12391bb26604e36ae4

I'm glad I could help. Closing issue ;)
