### ISSUE TITLE
my project in 2.9.8(cakephp) traying to upgrade to php8.. getting error

### ISSUE THREAD

**Issue by midaspriyabrata** [kamilwylegala/cakephp2-php8#16]
Uncaught Error: Unknown named parameter $subject in 

app/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php:128 Stack trace: #0 app/Vendor/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger() #1 app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch() #2 app/Vendor/cakephp/cakephp/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess() #3 app/Vendor/cakephp/cakephp/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController() #4 app/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct() #5 app/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php(269): ErrorHandler::handleException() #6 pp/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError() #7 app/Vendor/cakephp/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError() #8 app/Vendor/cakephp/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError() #9 [internal function]: App::shutdown() #10 {main} thrown in app/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php on line 128

**Comment by kamilwylegala** [comment]
Hey,

You have outdated CakePHP version.  Before PHP 8 you need to upgrade to latest available 2.* version of cake php, then migrate to this fork and then migrate PHP to 8.
