### ISSUE TITLE
hasAndBelongsToMany Relationships Not Working as Intended

### ISSUE THREAD

**Issue by rmarsh1ua** [kamilwylegala/cakephp2-php8#21]
When using a 'contain' parameter on a model find() operation, using a model that's associated with a hasAndBelongsToMany returns 0 associated entities, even when such an entity exists. Reading the database log, it's apparent that the correct query is running, and the database results contain the valid entity relationships but nothing is bound to the entities in CakePHP. This is using MySQL 5.7.38 and PHP 8.1.2. I've verified that the same thing is happening for a few different models. Other types of relationships are working fine, e.g. contain against a hasMany works as expected.

Here's an example from a model called User.

    public $hasAndBelongsToMany = array(
            'Committee' => array(
                'className'  => 'Committee',
                'joinTable'  => 'committees_users',
                'foreignKey' => 'user_id',
                'associationForeignKey' => 'committee_id',
                'unique'     => true
            )
     );

And running the query like this:

        $user = $this->User->find('first', array(
            'contain'=>array('Committee'),
            'conditions'=>array('id'=>$some_id)
        ));

**Comment by kamilwylegala** [comment]
Hey @rmarsh1ua Thanks for your contribution.

This fork's idea is about necessary fixes for Cake 2 that allow to work with newer PHP versions. The problem you described is about PHP8 only or does it occur also on older versions of PHP?

**Comment by rmarsh1ua** [comment]
Hey @kamilwylegala, thanks for the quick reply!

The app in question is migrating from standard Cake 2.x running on PHP 7.4 to this fork using PHP 8.1. Prior to the migration all of the code was working as intended, meaning that it must be because of some change in PHP8/this fork. It's still possible that there's some particular circumstances to how these models are being used that makes this an edge case, but I'm inclined to think that's not the case because it's happening for any HABTM type-relationship that I try.

**Comment by kamilwylegala** [comment]
Could you track this down? I'll be happy to merge the fix but currently I'm quite busy to do it on my own :hot_face:

**Comment by rmarsh1ua** [comment]
Totally understand your situation. In my shop, we're still evaluating the path to least resistance to solve our problem: either fix this bug or get PHP 7.4 to run in the container environment we're about to get locked into. I'm probably going to give this issue a few hours in the next few business days, and may or may not come back with a solution.

Cheers!

**Comment by kamilwylegala** [comment]
Thanks in advance! :blush:

**Comment by rmarsh1ua** [comment]
Turns out this was a problem related to our enterprise code + PHP 8.x with the way that typecasting worked in a root model class, so I don't think it has to do with any of the changes in this fork.

**Comment by nutjob4life** [comment]
Hi @kamilwylegala and @rmarsh1ua, sorry for "necro'ing" this, but I think I may be experiencing precisely this issue.

My app worked fine with CakePHP 2.x and PHP 7.4; my institute required me to upgrade to PHP 8.1 for security reasons, and _thank you so much for providing this repository_ which has simplified this process.

However, my `habtm` relationships aren't working; for example, when I try to add a `habtm`, I get the error:

    in_array(): Argument #2 ($haystack) must be of type array, null given

with stack trace
```
APP/Model/Behavior/ExtendAssociationsBehavior.php line 170 → in_array()
APP/Model/Behavior/ExtendAssociationsBehavior.php line 137 → ExtendAssociationsBehavior->unbindAll()
APP/Model/Behavior/ExtendAssociationsBehavior.php line 50 → ExtendAssociationsBehavior->__habtmFind()
CORE/Cake/Model/BehaviorCollection.php line 251 → ExtendAssociationsBehavior->habtmAdd()
CORE/Cake/Model/Model.php line 834 → BehaviorCollection->dispatchMethod()
APP/Controller/BiomarkersController.php line 671 → Model->__call()
[internal function] → BiomarkersController->addPublication()
CORE/Cake/Controller/Controller.php line 504 → ReflectionMethod->invokeArgs()
CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction()
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke()
APP/webroot/index.php line 134 → Dispatcher->dispatch()
```

Putting in debugging in both the PHP7.4 and PHP8.1 versions, I can see that `BehaviorCollection->dispatchMethod()` eventually calls `call_user_func_array` with identical parameters.

However, [these release notes for PHP8](https://www.php.net/manual/en/function.call-user-func-array) mention:

> args keys will now be interpreted as parameter names, instead of being silently ignored.

And the [wiki](https://wiki.php.net/rfc/named_params) further mentions (scroll down to `call_user_func_array`) mentions:

> For call_user_func_array(), this behavior constitutes a minor backwards-compatibility break: Previously, array keys were completely ignored by this function. Now, string keys will be interpreted as parameter names

Maybe this is a not-so-minor change? Does any of this sound—or even _feel_—familiar?

I'll work throughout the weekend on this but if you've got any nudges or hints, I'd appreciate it! I am _not_ a PHP developer 😝

EDIT: Maybe `call_user_func_array` is a red herring. Perhaps the issue is with the changed use of `@` in PHP8, which appears in this function in `habtm`'s `ExtendAssociationsBehavior.php`:
```php
    function unbindAll(&$model, $exceptions = array()) {
        $unbind = array();
        foreach($model->_associations as $type) {
            foreach($model->{$type} as $assoc=>$assocData) {
                // if the assoc is NOT in the exceptions list then
                // add it to the list of models to be unbound.
                if(@!in_array($assoc, $exceptions[$type])) {  // 👈 HERE?
                    $unbind[$type][] = $assoc;
                }
            }
        }
        // if we actually have models to unbind
        if(count($unbind) > 0) {
            $model->unbindModel($unbind);
        }
    }
```

EDIT 2: This seems to fix it:
```diff
--- a/app/Model/Behavior/ExtendAssociationsBehavior.php
+++ b/app/Model/Behavior/ExtendAssociationsBehavior.php
@@ -167,7 +167,11 @@ class ExtendAssociationsBehavior extends ModelBehavior {
             foreach($model->{$type} as $assoc=>$assocData) {
                 // if the assoc is NOT in the exceptions list then
                 // add it to the list of models to be unbound.
-                if(@!in_array($assoc, $exceptions[$type])) {
+
+                // PHP7:
+                // if(@!in_array($assoc, $exceptions[$type])) {
+                // PHP8:
+                if (!isset($exceptions[$type]) || !in_array($assoc, $exceptions[$type])) {
                     $unbind[$type][] = $assoc;
                 }
             }
```
Let me know if that looks okay—and thanks for letting me "think out loud" here ☺️

**Comment by kamilwylegala** [comment]
Hey @nutjob4life ! Thank you for such detailed description. Indeed, now it looks like backwards compatibility issue

I was fixing `call_user_func_array` before by applying `array_values` to the input.

Could you show me the basic setup to reproduce it? I don't use DB relationships via CakePHP in my project. But if you could give me a minimal setup to reproduce, I could debug this too. Unless it's very similar to what @rmarsh1ua described in first post.

I'm reopening the issue :blush:

**Comment by nutjob4life** [comment]
Sorry @kamilwylegala I'm really not a PHP developer* so I can't provide a small test case.

But the essential issue is just usage: `@` is apparently _not considered best practice_ in PHP. As one Gerry Wastaken wrote:

> Error suppression should be avoided if possible as it doesn't just suppress the error that you are trying to stop, but will also suppress errors that you didn't predict would ever occur. This will make debugging a nightmare.

True words! And CakePHP is not the first instance of `@` [that gave me a headache](https://github.com/rockiger/reactpress) (and was later fixed).

And further, in PHP7, `@` suppressed more error conditions than in PHP8. One of those error conditions came from de-referencing an unfound item in an "array' (ahem) before passing it into a function. So in the earlier PHP7 version of `ExtendAssociationsBehavior.php`, the `@` greatly abbreviated the notion of "if the $assoc is not found in the $exceptions array entry for $type—_or if there is no_ $type in $exceptions—then execute the condition"
```php
if (@!in_array($assoc, $exceptions[$type])) 
```
The diff for PHP8 removes the `@` and makes it explicit: "if there is no $type in $exceptions _or_ if the $assoc does not occur in the $type in $exceptions, then execute the condition".
```php
if (!isset($exceptions[$type]) || !in_array($assoc, $exceptions[$type]))
```
Sound good? 😊

*Ask me how I really feel and I'll provide a 5000 word diatribe about it 😝

**Comment by kamilwylegala** [comment]
Hey @nutjob4life 

I started looking at this issue.

I totally missed that during reading your comment initially. 

The fix you suggested is in class that belongs to your app. `ExtendAssociationsBehavior` is not related to the framework. In that case, please apply fix in your repository. 

I suggest doing it in the following way:

```diff
--- a/app/Model/Behavior/ExtendAssociationsBehavior.php
+++ b/app/Model/Behavior/ExtendAssociationsBehavior.php
@@ -167,7 +167,11 @@ class ExtendAssociationsBehavior extends ModelBehavior {
             foreach($model->{$type} as $assoc=>$assocData) {
                 // if the assoc is NOT in the exceptions list then
                 // add it to the list of models to be unbound.
-                if(@!in_array($assoc, $exceptions[$type])) {
+               $exceptionsForType = is_array($exceptions[$type] ?? null) ? $exceptions[$type] : [];
+                if (!in_array($assoc, $exceptionsForType)) {
                     $unbind[$type][] = $assoc;
                 }
             }
```
