### ISSUE TITLE
Relative time may not be cached if specified in CacheHelper duration

### ISSUE THREAD

**Issue by tenkoma** [kamilwylegala/cakephp2-php8#26]
This Issue summarizes the details of the defects for the tests marked as incomplete in #23.
https://github.com/kamilwylegala/cakephp2-php8/pull/23/commits/89fc8c96409c65bfbb927b8a809d9707eb7e35d5

# Description
When using `CacheHelper` to cache views, if specify a relative time for `duration`, the view may not be cached in PHP 8.0+.

## How to reproduce the defect
Follow the steps in [CacheHelper - 2.x (Using the Helper)](https://book.cakephp.org/2/en/core-libraries/helpers/cache.html#using-the-helper) to make the cache available.
Next, create the controller and template.

### `app/Controller/PostsController.php`
```php
<?php
App::uses('AppController', 'Controller');

class PostsController extends AppController {
    public $uses = array();
    public $helpers = array('Cache');

    // Shorthand notation for specifying the same duration for all actions.
    public $cacheAction = '+10 seconds';

    public function index() {}
}
```

### `app/View/Posts/index.ctp`
```php
cached at <?= date('H:i:s'); ?>
```
Then go to `http://webserver/posts`.
If you reload the page repeatedly, the time display should not change for 10 seconds, but it does.

# PHP Version
`8.0.27`

# Temporary workaround
Can work around this by specifying the following in the duration.
* `$cacheAction = 10;` (Specified by integer)
* `$cacheAction = '10 seconds'` (Specify in a relative time string such that it begins with a number)

**Comment by kamilwylegala** [comment]
Thank you for your contribution! :blush: 

I will look at it closer to the end of the week.

**Comment by kamilwylegala** [comment]
PR merged to master.
