### ISSUE TITLE
PaginatorHelper::numbers() renders extra separator string

### ISSUE THREAD

**Issue by tenkoma** [kamilwylegala/cakephp2-php8#29]
This Issue summarizes the details of the defects for the tests marked as incomplete in #23
https://github.com/kamilwylegala/cakephp2-php8/pull/23/commits/a597f35beac7777ece68a9f3fa242cc531cdaa0e

# Description
When using `PaginatorHelper::numbers()` to create page number links, if `$option['last']` is a label string instead of an offset number, an extra separator string is output.

### Creata table, insert records, and PHP codes

Because the code is long, it is folded in `<details>`.

<details>
<summary>Details</summary>

#### Create `posts` table and insert data
The `INSERT` statement is executed many times until there are 30+ records.

```mysql
CREATE DATABASE IF NOT EXISTS cakephp;

CREATE TABLE IF NOT EXISTS posts
(
    id       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title    VARCHAR(50),
    body     TEXT,
    created  DATETIME NOT NULL
);

-- The INSERT statement is executed many times until there are 30 or more records.
INSERT INTO posts (title, body, created)
VALUES
    ('The title', 'This is the post body.', NOW()),
    ('A title once again', 'And the post body follows.', NOW()),
    ('Title strikes back', 'This is really exciting! Not.', NOW())
;
```

#### `app/Config/database.php`

```php
<?php
class DATABASE_CONFIG {
    public $default = array(
        'datasource' => 'Database/Mysql',
        'host' => 'dev-db',
        'login' => 'root',
        'password' => 'root',
        'database' => 'cakephp',
    );
}
```

#### `app/Controller/PostsController.php`

```php
<?php  
App::uses('AppController', 'Controller');  
  
class PostsController extends AppController {  
   public $uses = array('Post');  
   public $components = array('Paginator');  
   public $paginate = array(  
      'limit' => 2,  
      'order' => array('Post.id' => 'asc')  
   );  
  
   public function index() {  
      $this->Paginator->settings = $this->paginate;  
      $posts = $this->Paginator->paginate('Post');  
      $this->set('posts', $posts);  
   }  
}
```

#### `app/View/Posts/index.ctp`

```php
<h2>Posts</h2>  
<?php foreach ($posts as $post) { ?>  
<dl><dt><?= h($post['Post']['title']) ?></dt><dd><?= h($post['Post']['body']) ?></dd></dl>  
<?php } ?>  
<h3>Defect example (1)</h3>  
<h4>Code:</h4>  
<pre>$this-&gt;Paginator-&gt;numbers(true);</pre>  
<?php  
// The preceding code is shorthand for the following code.  
// $this->Paginator->numbers(array(  
//      'before' => ' | ', 'after' => ' | ', 'first' => 'first', 'last' => 'last'  
// ));  
?>  
<h4>output:</h4>  
<p><?= $this->Paginator->numbers(true) ?></p>  
  
<h3>Defect example (2): Explicitly specify labels</h3>  
<h4>code:</h4>  
<pre>$this-&gt;Paginator-&gt;numbers(  
   array('before' => ' | ', 'after' => ' | ', 'first' => 'First page', 'last' => 'Last page'));</pre>  
<h4>output:</h4>  
<p><?= $this->Paginator->numbers(array(  
      'before' => ' | ', 'after' => ' | ', 'first' => 'First page', 'last' => 'Last page'  
   )) ?></p>
```

</details>

### View the page in web browser

When you access `http://webserver/posts/index/page:8`, your web browser will display the following

![image](https://user-images.githubusercontent.com/16202/215329878-11b8184e-510a-4fed-9748-7eed414a7930.png)

# PHP Version
`8.0.27`

# Temporary workaround

There may be no easy way to do this...
Add a helper class that extends `PaginatorHelper` to `app/View/Helper` (e.g. as `AppPaginatorHelper`) and modify `numbers()` as in #30.
Then, in the `$helpers` of the controller you want to use
Define it to be available under the alias `Paginator`.
```php
    public $helpers = array(
        'Paginator' => array(
            'className' => 'AppPaginator'
        )
    );
```
ref: https://book.cakephp.org/2/en/views/helpers.html#using-and-configuring-helpers

**Comment by kamilwylegala** [comment]
PR merged. Thanks!
