### ISSUE TITLE
Unsupported operand types: float + string

### ISSUE THREAD

**Issue by Jijarine** [kamilwylegala/cakephp2-php8#39]
When calling an element:

`$this->element($file, $data);`

I receive "Unsupported operand types: float + string"

STACK TRACE
[CORE/Cake/View/View.php line 971] → [include()]
[CORE/Cake/View/View.php line 933] → [View->_evaluate()]
[CORE/Cake/View/View.php line 1224] → [View->_render()]
[CORE/Cake/View/View.php line 418] → [View->_renderElement()]
[APP/Plugin/Samples/View/Elements/potency.ctp line 448] → [View->element()]
[CORE/Cake/View/View.php line 971] → [include(string)]
[CORE/Cake/View/View.php line 933] → [View->_evaluate()]
[CORE/Cake/View/View.php line 1224] → [View->_render()]
[CORE/Cake/View/View.php line 418] → [View->_renderElement()]
[APP/Plugin/Samples/View/Potencies/view.ctp line 1] → [View->element()]
[CORE/Cake/View/View.php line 971] → [include(string)]
[CORE/Cake/View/View.php line 933] → [View->_evaluate()]
[CORE/Cake/View/View.php line 473] → [View->_render()]
[CORE/Cake/Controller/Controller.php line 973] → [View->render()]
[CORE/Cake/Routing/Dispatcher.php line 200] → [Controller->render()]
[CORE/Cake/Routing/Dispatcher.php line 167] → [Dispatcher->_invoke()]
[APP/webroot/index.php line 109] → [Dispatcher->dispatch()]

Thoughts? Due to the way the client requests I have to render the view which calls an element, which in turn calls a separate element. I've done a var dump, there is no mismatch. I'm very confused.

**Comment by Jijarine** [comment]
let me correct myself, when you name a variable it causes this error.

`$this->element($file, ['data' => $data]);`

Outside of a plugin, `$this->element($file, $data);` works as expected. In a plugin the variable is not passed unless it is specifically declared like in the first code statement. If you do not declare it, nothing is passed. $data is empty.

**Comment by Jijarine** [comment]
I was thinking maybe a variable was being changed to a string then if was used in an equation it would trigger "Unsupported operand types: float + string". I was correct, but the stack trace lead me to believe it was a code error. 2.X really needs a better error reporting system. I would prefer PHP to puke in response with an error log or me tell me SPECIFICALLY where it was wrong instead of a vague reference to an element.

SOLVED. Feel free to delete this or keep it in case someone has a similar issue.

**Comment by kamilwylegala** [comment]
Hey @Jijarine Thanks for creating the issue. I'm glad you figured out the solution. Let's keep it. I bet it will be useful for others. :blush:
