### ISSUE TITLE
Add support for PHP 8.2?

### ISSUE THREAD

**Issue by lonormaly** [kamilwylegala/cakephp2-php8#41]
Is there a way to add support for PHP 8.2?

**Comment by kamilwylegala** [comment]
Hey, I migrated my project to 8.2 and fork works fine. Although I get deprecation notices about undeclared properties. This is something that needs to be addressed before PHP9.

Update your project too and let me know if there are any problems :)

**Comment by lonormaly** [comment]
@kamilwylegala The only problem I encountered was with mcrypt that isn't supported anymore.
Also, before using this repo the integers were returned as strings, for example table's id's, but after the upgrade they're returned as ints. any idea why?

**Comment by kamilwylegala** [comment]
@lonormaly I believe this is caused by this: https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.pdo.mysql

Please take a look at this commit https://github.com/kamilwylegala/cakephp2-php8/commit/071b292969ed26c85167fd6fa23912fb90c2a09f
