### ISSUE TITLE
On PHP 7.3 instead of 7.4 OK?

### ISSUE THREAD

**Issue by jmcpheters** [kamilwylegala/cakephp2-php8#42]
Not really an issue, but an question...

The readme says:

> Only prerequisite is to have your application already on PHP 7.4.

Do you think it will work if the application is on PHP 7.3? I ask because for the version of Linux I'm using, the yum repository only has PHP 7.3 as the latest 7.x available, and I don't want to build PHP 7.4 from scratch if I don' t have to...

Advice?

**Comment by kamilwylegala** [comment]
Going straight to PHP 8 from PHP 7.3 should be fine. I don't recall any significant breaking changes in PHP 7.4 that are worth taking care separately.
