### ISSUE TITLE
How to use this fork?

### ISSUE THREAD

**Issue by kirti-u** [kamilwylegala/cakephp2-php8#44]
Sorry, this is not an issue regarding your fork. but, i haven't find any other way to contact you.
i am new on Github.
i built a cakephp project long time ago. now it is not working on php8. so i found this link for solution but i don't know how to use it?
is it ilke, i have to download this directory and after that will have to copy paste all my files (controller, model, view, webroot etc)  into this?
please can you explain?
Thank you.

**Comment by kamilwylegala** [comment]
Hey, do you use composer in your project? If not yet, I recommend to setup it first. :blush:  

Next step is to install it via composer. To do so, you need to modify `composer.json`. Make sure you have eg.
```
"require": {
    "cakephp/cakephp": "dev-master as 2.10.24",
},
//...
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/kamilwylegala/cakephp2-php8"
        },
}
```

Thanks to that you tell composer to download cakephp from `master` branch from this fork.

**Comment by kirti-u** [comment]
Thanks for the reply.
on 'composer install' command i get the following error:

[RuntimeException]
  Root package 'cakephp/cakephp' cannot require itself in its composer.json
  Did you accidentally name your root package after an external package?

**Comment by kamilwylegala** [comment]
You need to make `cakephp/cakephp` a dependency of your project, you don't need to copy this repository to your project.

Are you familiar how dependencies management with composer work?

**Update:**

Here is for example part of composer.json for my project:
```json
{
    "name": "kwylegala/panel",
    "license": "proprietary",
    "scripts": {
        "php-cs-fixer": "php-cs-fixer --rules=@PSR2,-single_blank_line_at_eof"
    },
    "require": {
        "php": "^8.2",
        "ext-pdo": "*",
        "ext-json": "*",
        "ext-intl": "*",
        "ext-fileinfo": "*",
        "ext-openssl": "*",
        "ext-apcu": "*",
        "ext-memcached": "*",
        "cakephp/cakephp": "dev-master as 2.10.24"
    },
```

**Comment by kirti-u** [comment]
Here is part of composer.json of my project:

```
{
	"name":` "cakephp/cakephp",
	"description": "The CakePHP framework",
	"type": "library",
	"keywords": ["framework"],
	"homepage": "https://cakephp.org",
	"license": "MIT",
	"authors": [
		{
			"name": "CakePHP Community",
			"homepage": "https://github.com/cakephp/cakephp/graphs/contributors"
		}
	],
	"support": {
		"issues": "https://github.com/cakephp/cakephp/issues",
		"forum": "https://stackoverflow.com/tags/cakephp",
		"irc": "irc://irc.freenode.org/cakephp",
		"source": "https://github.com/cakephp/cakephp"
	},
	"require": {
		"php": ">=5.3.0",
		"cakephp/cakephp": "dev-master as 2.10.24"
	},
```

**Comment by kamilwylegala** [comment]
This is composer.json of cakephp framework. You need to first create basic config with `composer init` and then you add dependencies via `composer require`.

Please take a look here: https://phptherightway.com/#composer_and_packagist

**Comment by kirti-u** [comment]
but if create basic config with composer init, it will overwrite the cakephp framework's composer.json file!

**Comment by kamilwylegala** [comment]
Sorry but I don't know how you setup your project. You need to provide more details.

**Comment by kirti-u** [comment]
I have already cakephp version 2 application built. And it is not working
on php8.
So, composer.json file is already there as I sent you the part of it.


Thanks and regards,
Kirti Umrigar

**Comment by kamilwylegala** [comment]
Indeed, composer.json that you showed belongs to the framework, not your project. You're not supposed to modify it. It looks you copy-pasted whole framework to your project, please do the same with this fork.
