### ISSUE TITLE
How to add new package?

### ISSUE THREAD

**Issue by luqmansolihin** [kamilwylegala/cakephp2-php8#45]
I have 2 composer in root project and directory of app. How to add new package and using in controller?

**Comment by kamilwylegala** [comment]
Hey, please take a look at readme: https://github.com/kamilwylegala/cakephp2-php8#installation

**Comment by luqmansolihin** [comment]
maybe my question is still general. just get to the point of my question, I want to add the firebase/php-jwt library, how do I add it and call it in the controller?

**Comment by VaelVictus** [comment]
Then ask it in a general place. Here, I pasted your question into an AI.

https://chat.openai.com/share/e3923a53-91b0-4e29-baff-6a4548bedbde
