### ISSUE TITLE
notEmpty() deprecated

### ISSUE THREAD

**Issue by rgPakora** [kamilwylegala/cakephp2-php8#48]
Hello,

First massive thanks for your work.
Maybe deprecated function are not the priority and even won't be solved in the future.
I'm not sure if i have the skills to contribute so maybe i'll let more qualidifed people to solve this if possible.

[Deprecated (16384)](javascript:void(0);): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [CORE/Cake/Utility/Validation.php, line 60]

Best,

**Comment by kamilwylegala** [comment]
Hey @rgPakora Sorry for late response.

I don't see this function is used by framework itself. I think it's a matter of replacing of `notEmpty` with `notBlank` in your application code.

Although I don't plan to remove deprecated functions in this fork, I will leave this function for backwards compatibility.

Feel free to reopen if you meant something else.
