### ISSUE TITLE
Problem with debugkit

### ISSUE THREAD

**Issue by impronta48** [kamilwylegala/cakephp2-php8#53]
If I enable debug =1 and debugkit I get a lot of rubbish on my screen (as if jquery could not be called).
Is this happening only to me? Anybody found a solution?

Thanks
Massimo

**Comment by kamilwylegala** [comment]
Could you share screen shot? Is it php stack trace or you get JS errors in console?

**Comment by impronta48** [comment]
Is it php stack trace , I removed debug kit in order to solve... not so bad ;-)

**Comment by kamilwylegala** [comment]
So all good? Can I close the issue? :)
