### ISSUE TITLE
Require intl extension as a dependency on this repo

### ISSUE THREAD

**Issue by diegosurita** [kamilwylegala/cakephp2-php8#65]
As I mentioned on PR https://github.com/kamilwylegala/cakephp2-php8/pull/64, CakePHP 2 docs don't require `intl` PHP extension.
I oppened this issue to discuss the possibility to add `intl` as an requirement on this repo. With `intl` we can stop hidding `strftime` warning deprecations.

**Comment by kamilwylegala** [comment]
Hey @diegosurita 

Introducing Intl would be a breaking change in the framework. But hey... fork is about support of newest PHP versions. In my project I already use Intl, so from my perspective it's totally fine.

I think we could first put a note to the readme file, that we plan to add `Intl` requirement and link here to this issue. Devs will have a chance to comment on that. If no concerns from others,  I think we could commit the Intl requirement to the code base in few months.

What do you think?

**Comment by diegosurita** [comment]
Hey!
Yeah I already use it too.

> I think we could first put a note to the readme file, that we plan to add Intl requirement and link here to this issue. Devs will have a chance to comment on that. If no concerns from others, I think we could commit the Intl requirement to the code base in few months.

That sounds perfect!

**Comment by diegosurita** [comment]
Ok.
@kamilwylegala do you think we can put a date to do this change and add it on the note? If yes, what date would it be?

**Comment by kamilwylegala** [comment]
I just updated the readme file. Beginning of May 2024 sounds OK? We will have 3 months to gather any feedback here. If no objections from others, let's just start rolling this out :raised_hands:

**Comment by diegosurita** [comment]
Yeah that sounds perfect 🙌🏼

**Comment by kamilwylegala** [comment]
@diegosurita I think it's the time: https://github.com/kamilwylegala/cakephp2-php8/pull/69 :blush:

**Comment by diegosurita** [comment]
Hey! I left a comment on you PR.
